# Generated by Django 5.2 on 2025-05-02 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('life', 'Lifestyle'), ('edu', 'Education'), ('biz', 'Business'), ('news', 'News')], max_length=100)),
                ('comments', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
