# Generated by Django 5.2 on 2025-05-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_comments_blog_created_at_blog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50000),
        ),
    ]
